version: "3.9"
services:
  my-nginx:
    image: nginx
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-logs:/var/logs
      - ../image-serve-path:/www/data:ro
      - ../frontend/dist:/www/frontend:ro
